# Generated by Django 5.1 on 2024-09-04 04:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade_perguntas', models.IntegerField(default=0)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='RespondidoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(limit_choices_to={'groups__name': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questioniaro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario')),
            ],
        ),
        migrations.AddField(
            model_name='questionario',
            name='respondido_por',
            field=models.ManyToManyField(through='questionario.RespondidoPor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('avaliado', models.BooleanField(default=0)),
                ('nota', models.IntegerField(null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'groups__name': 'Aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.pergunta')),
            ],
        ),
    ]
