# Generated by Django 5.1 on 2024-09-01 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='abertura',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='questionario',
            name='fechamento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='questionario',
            name='quantidade_perguntas',
            field=models.IntegerField(default=0),
        ),
    ]
