# Generated by Django 5.1 on 2024-09-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondidopor',
            name='avaliado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='respondidopor',
            name='nota',
            field=models.FloatField(null=True),
        ),
    ]
