# Generated by Django 5.1 on 2024-09-01 04:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_questionario_abertura_questionario_fechamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='abertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='fechamento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
