# Generated by Django 5.1 on 2024-09-01 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_alter_questionario_abertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='respondido_por',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Aluno'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
