# Generated by Django 5.1 on 2024-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_rename_questioniaro_respondidopor_questionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
