# Generated by Django 5.1 on 2024-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_questionario_respondido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
