# Generated by Django 5.1 on 2024-08-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
