# Generated by Django 5.1 on 2024-08-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='ra_professor',
            new_name='professor',
        ),
    ]
