# Generated by Django 5.1 on 2024-08-23 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_ra_professor_turma_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Aluno'}, related_name='alunos_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
